# Generated by Django 5.2 on 2025-04-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price_today', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('price_week_ago', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('price_month_days_ago', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('date_type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_prices', to='metals_app.metal')),
            ],
            options={
                'unique_together': {('metal', 'currency', 'date_type')},
            },
        ),
    ]
