# Generated by Django 5.2 on 2025-04-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metals_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalprice',
            name='currency_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
