# Generated by Django 5.2 on 2025-06-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metals_app', '0003_metalpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalprice',
            name='currency_name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
